[package]
name = "DATA"
version = "0.1.0"
authors = ["Your Name <your.email@example.com>"]
description = "Your Julia toolkit for streamlined data exploration and transformation."
license = "MIT"
uuid = "12345678-1234-5678-1234-567812345678"
repo = "https://github.com/yourusername/DATA.jl"

[dependencies]
Julia = "1.5"
CSV = "0.8.5"
DataFrames = "1.2.0"

[compat]
Julia = "1.5"
CSV = "0.8.5"
DataFrames = "1.2.0"
